services:
    hlpnebula.json_builder:
        class: HLP\NebulaBundle\JSONBuilder\JSONBuilder
        calls:
            - [setRequest, [@request_stack]]
        
    hlpnebula.knossos_server_connect:
        class: HLP\NebulaBundle\KSConnect\KSConnect
        arguments: ['%server%', '%key%', '%secure%']
